AWSTemplateFormatVersion: 2010-09-09
Description: >-
  website-change-monitor

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  checkWebPage:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: check-web-page-checkWebPage
      Handler: dist/handlers/check-web-page.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that checks a web page for changes
      Policies:
        - AWSLambdaBasicExecutionRole
